spring.datasource.url=jdbc:postgresql://localhost:5432/staynest

spring.datasource.username=postgres

spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
server.port=8081
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secretKey=mySuperSecretKeyForStayNestApplication123456789

stripe.secret=${STRIPE_SECRET}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
frontend.url=http://localhost:3000